name: Test Secrets

on:
  workflow_dispatch:   # 수동 실행용

jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Show masked secrets
        run: |
          echo "Bot token: $TELEGRAM_BOT_TOKEN"
          echo "Chat ID: $TELEGRAM_CHAT_ID"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
